src/main/java/com/yujigyeongseong/api/domain/research_number/controller/ResearchNumberController.java, src/main/webapp/WEB-INF/views/research-number/research-number-page.jsp, src/main/webapp/resources/css/common/global.css, src/main/webapp/resources/css/research_number/research-number.css
<br/>
- 연구자 번호 발급 페이지 화면 조회 API 추가
- 연구자 번호 발급 페이지 UI 구현
<br/>
<br/>
- Close #4
<br/>
=> 연구자 번호 발급페이지를 구현한다.

package-lock.json, src/main/java/com/yujigyeongseong/api/domain/announcement/controller/AnnouncementController.java, src/main/webapp/WEB-INF/views/announcement/announcement-list.jsp, src/main/webapp/resources/css/announcement/announcement.css, src/main/webapp/resources/css/common/global.css
<br/>
- 공고 목록 페이지 화면 조회 API 추가
- 공고 목록 페이지 화면 UI 구현 
<br/>
<br/>
- Close #3 
<br/>
=> 공고 목록 페이지를 구현한다.

src/main/webapp/WEB-INF/views/research-number/research-number-page.jsp, src/main/webapp/resources/css/research-number/research-number.css
- [] FE
- [] BE
<br/>
- 폴더 이름 변경
- 주석 제거, 정렬
<br/>
<br/>
- Close #4
<br/>
=> 연구자 번호 발급페이지를 구현한다

src/main/webapp/WEB-INF/views/announcement/announcement-list.jsp, src/main/webapp/resources/css/announcement/announcement.css
- [] BE
<br/>
- 공고 목록 페이지의 UI 수정 및 주석 제거
<br/>
<br/>
- Close #15
<br/>
=> 공고 목록 페이지의 UI를 수정한다.

src/main/webapp/WEB-INF/views/work-lounge/evaluation-paper.jsp, src/main/webapp/resources/css/work-lounge/evaluation-paper.css, src/main/webapp/resources/js/work-lounge/evaluation-paper.js
<br/>
- 평가보고서 페이지 화면 조회 API 추가
- 평가보고서 페이지 UI 구현
<br/>
<br/>
- Close #12 
<br/>
=> 워크라운지(평가과제목록) 평가 보고서 페이지 UI 구현한다.

src/main/webapp/WEB-INF/views/rnd-plan/rsrch-institution.jsp, src/main/webapp/WEB-INF/views/rnd-plan/task-summary.jsp, src/main/webapp/resources/css/common/global.css, src/main/webapp/resources/css/rnd-plan/basic.css
<br/>
- 연구개발계획서(연구기관) 페이지 UI를 구현
- 동적 기능 구현 필요
<br/>
<br/>
- Close #21 
<br/>
=> 연구개발계획서(연구기관) 페이지 UI를 구현한다.

src/main/java/com/yujigyeongseong/api/domain/research_number/controller/ResearchNumberController.java, src/main/webapp/WEB-INF/views/common/common-work-lounge-tap.jsp, src/main/webapp/WEB-INF/views/research-number/research-number-page.jsp, src/main/webapp/WEB-INF/views/work-lounge/business-timeline.jsp, src/main/webapp/resources/css/common/common-work-lounge-tap.css, src/main/webapp/resources/css/research-number/research-number.css, src/main/webapp/resources/js/research-number/research-number.js
- [] BE
<br/>
- 워크라운지 공통 탭 구현
- 연구자 번호 발급 페이지 모달창 구현
<br/>
<br/>
- Close #23
- #11
<br/>
=> 워크라운지 공통 탭을 구현한다.

src/main/webapp/WEB-INF/views/work-lounge/register-list.jsp, src/main/webapp/resources/css/work-lounge/register-list.css
<br/>
- 워크라운지 접수목록 페이지 구현
<br/>
<br/>
- Close #27 
<br/>
=> 워크라운지 접수목록 페이지를 구현한다.

src/main/java/com/yujigyeongseong/api/domain/research_number/controller/ResearchNumberController.java, src/main/webapp/WEB-INF/views/research-number/eval-committee-register.jsp, src/main/webapp/resources/css/research-number/eval-committee-register.css, src/main/webapp/resources/js/research-number/eval-committee-register.js
- [] BE
<br/>
- 후보단 등록 페이지 UI 구현
<br/>
<br/>
- Close #25
<br/>
=> 후보단 등록 페이지 UI를 구현한다.

src/main/java/com/yujigyeongseong/api/domain/announcement/controller/AnnouncementController.java, src/main/webapp/WEB-INF/views/announcement/announcement-list.jsp, src/main/webapp/WEB-INF/views/announcement/detailed-notice.jsp, src/main/webapp/resources/css/announcement/announcement.css, src/main/webapp/resources/css/announcement/detailed-notice.css
- [] BE
<br/>
- 사업공고 페이지 UI 구현
<br/>
<br/>
- Close #17
<br/>
=> 사업공고 페이지 UI를 구현한다.

src/main/webapp/WEB-INF/views/work-lounge/business-timeline.jsp, src/main/webapp/resources/css/work-lounge/business-timeline.css, src/main/webapp/resources/js/work-lounge/business-timeline.js
- [] BE
<br/>
- 워크라운지의 업무타임라인 페이지 UI 구현
<br/>
<br/>
- Close #30
<br/>
=> 워크라운지 업무타임라인 페이지 UI를 구현한다.

src/main/java/com/yujigyeongseong/api/domain/announcement/controller/AnnouncementController.java, src/main/java/com/yujigyeongseong/api/domain/research_number/controller/ResearchNumberController.java, src/main/webapp/WEB-INF/views/announcement/apply-for-notice.jsp, src/main/webapp/resources/css/announcement/apply-for-notice.css
- [] FE
- [] BE
<br/>
- 공고분야 접수 페이지 UI를 구현한다.
<br/>
<br/>
- Close #34 
<br/>
=> 공고분야 접수 페이지 UI를 구현한다.

src/main/java/com/yujigyeongseong/api/domain/work_lounge/controller/WorkLoungeController.java, src/main/webapp/WEB-INF/views/common/common-work-lounge-tap.jsp, src/main/webapp/WEB-INF/views/work-lounge/selection-evaluation.jsp, src/main/webapp/resources/css/work-lounge/selection-evaluation.css, src/main/webapp/resources/js/work-lounge/selection-evaluation.js
<br/>
- 선정 평가 목록 페이지 구현
<br/>
<br/>
- Close #39 
<br/>
=> 선정 평가 목록 페이지를 구현한다.

src/main/java/com/yujigyeongseong/api/domain/work_lounge/controller/WorkLoungeController.java, src/main/webapp/WEB-INF/views/common/common-work-lounge-tap.jsp, src/main/webapp/WEB-INF/views/work-lounge/bubble-chart.jsp, src/main/webapp/WEB-INF/views/work-lounge/radar-chart.jsp, src/main/webapp/WEB-INF/views/work-lounge/selection-evaluation-detail.jsp, src/main/webapp/WEB-INF/views/work-lounge/selection-evaluation.jsp, src/main/webapp/resources/css/work-lounge/selection-evaluation-detail.css, src/main/webapp/resources/css/work-lounge/selection-evaluation.css, src/main/webapp/resources/js/work-lounge/selection-evaluation-detail.js, src/main/webapp/resources/js/work-lounge/selection-evaluation.js
<br/>
- 선정 평가 상세 페이지 구현
<br/>
<br/>
- Close #44 
<br/>
=> 선정 평가 상세 페이지 UI를 구현한다.

src/main/java/com/yujigyeongseong/api/domain/work_lounge/controller/WorkLoungeController.java, src/main/webapp/WEB-INF/views/research-number/research-number-page.jsp, src/main/webapp/WEB-INF/views/work-lounge/eval-committee-compose.jsp, src/main/webapp/resources/css/research-number/research-number.css, src/main/webapp/resources/css/work-lounge/eval-committee-compose.css, src/main/webapp/resources/js/research-number/research-number.js, src/main/webapp/resources/js/work-lounge/eval-committee-compose.js
- [] BE
<br/>
- 워크라운지 평가위원회 구성 페이지 UI 구현
- 연구자 번호 발급 페이지 기술분야 트리 수정
<br/>
<br/>
- Close #38
<br/>
=> 워크라운지 평가위원회 구성 페이지를 구현한다.

src/main/java/com/yujigyeongseong/api/domain/announcement/controller/AnnouncementController.java, src/main/java/com/yujigyeongseong/api/domain/member/controller/MemberSignIn.java, src/main/webapp/WEB-INF/views/sign-in-sign-up/sign-in.jsp, src/main/webapp/WEB-INF/views/sign-in-sign-up/sign-up-1.jsp, src/main/webapp/WEB-INF/views/sign-in-sign-up/sign-up-2.jsp, src/main/webapp/WEB-INF/views/sign-in-sign-up/sign-up-3.jsp, src/main/webapp/WEB-INF/views/sign-in-sign-up/sign-up-4.jsp, src/main/webapp/resources/css/sign-in-sign-up/sign-in.css, src/main/webapp/resources/css/sign-in-sign-up/sign-up-1.css, src/main/webapp/resources/css/sign-in-sign-up/sign-up-2.css, src/main/webapp/resources/css/sign-in-sign-up/sign-up-3.css, src/main/webapp/resources/css/sign-in-sign-up/sign-up-4.css
- [] BE
<br/>
- 로그인 페이지 UI 구현
- 회원가입 - 본인인증 페이지 UI 구현
- 회원가입 - 약관동의 페이지 UI 구현
- 회원가입 - 가입양식 작성 페이지 UI 구현
- 회원가입 - 가입완료 페이지 UI 구현
<br/>
<br/>
- Close #이슈번호
<br/>
=> 회원가입 로그인 UI를 구현한다.

src/main/java/com/yujigyeongseong/api/domain/research_number/controller/EvalCommitteeRestController.java, src/main/java/com/yujigyeongseong/api/domain/research_number/controller/ResearchNumberController.java, src/main/java/com/yujigyeongseong/api/domain/research_number/dao/EvalCommitteeMapper.java, src/main/java/com/yujigyeongseong/api/domain/research_number/dto/AcadAbility.java, src/main/java/com/yujigyeongseong/api/domain/research_number/dto/Career.java, src/main/java/com/yujigyeongseong/api/domain/research_number/dto/techField.java, src/main/java/com/yujigyeongseong/api/domain/research_number/service/EvalCommitteeService.java, src/main/java/com/yujigyeongseong/api/domain/research_number/service/EvalCommitteeServiceImpl.java, src/main/resources/api/mapper/h2/evalCommittee.xml, src/main/resources/data-h2.sql, src/main/webapp/WEB-INF/views/research-number/eval-committee-register.jsp, src/main/webapp/WEB-INF/views/research-number/research-number-page.jsp, src/main/webapp/WEB-INF/views/work-lounge/business-timeline.jsp, src/main/webapp/resources/css/research-number/eval-committee-register.css, src/main/webapp/resources/css/research-number/research-number.css, src/main/webapp/resources/css/work-lounge/business-timeline.css, src/main/webapp/resources/css/work-lounge/eval-committee-compose.css, src/main/webapp/resources/js/research-number/eval-committee-register.js, src/main/webapp/resources/js/research-number/research-number.js, src/main/webapp/resources/js/work-lounge/business-timeline.js, src/main/webapp/resources/js/work-lounge/eval-committee-compose.js
<br/>
- 학력 추가 칸 수정
- DB 연결
- 후보단 페이지 DB 조회
- 업무타임라인 필터 기능 수정
<br/>
<br/>
- Close #47
<br/>
=> 후보단 등록 페이지 UI 수정 및 DB를 연결한다.

src/main/webapp/WEB-INF/views/common/common-header.jsp, src/main/webapp/WEB-INF/views/rnd-plan/basic.jsp, src/main/webapp/WEB-INF/views/rnd-plan/common-rnd-progress.jsp, src/main/webapp/WEB-INF/views/rnd-plan/rsrch-institution.jsp, src/main/webapp/WEB-INF/views/rnd-plan/task-summary.jsp, src/main/webapp/resources/css/rnd-plan/common-rnd.css, src/main/webapp/resources/js/rnd-plan/basic.js, src/main/webapp/resources/js/rnd-plan/common-rnd-control.js, src/main/webapp/resources/js/rnd-plan/task-summary.js
<br/>
<br/>
<br/>
- Close #33 
<br/>
=> 연구개발계획서(과제요약) 동적 기능 추가 및 연구기관 페이지 UI 구현

src/main/java/com/yujigyeongseong/api/domain/research_number/controller/ResearchNumberController.java, src/main/java/com/yujigyeongseong/api/domain/research_number/dao/EvalCommitteeMapper.java, src/main/java/com/yujigyeongseong/api/domain/research_number/dto/memTechField.java, src/main/java/com/yujigyeongseong/api/domain/research_number/service/EvalCommitteeService.java, src/main/java/com/yujigyeongseong/api/domain/research_number/service/EvalCommitteeServiceImpl.java, src/main/resources/api/mapper/h2/evalCommittee.xml, src/main/resources/data-h2.sql, src/main/webapp/WEB-INF/views/research-number/eval-committee-register.jsp
<br/>
- 후보단 신청 페이지 기술분류 데이터 추가
- 후보단 페이지의 기술분류 조회
<br/>
<br/>
- Close #53
<br/>
=> 후보단 신청 페이지 기술분류를 구현한다.

src/main/java/com/yujigyeongseong/api/domain/research_number/controller/EvalCommitteeRestController.java, src/main/java/com/yujigyeongseong/api/domain/research_number/dao/EvalCommitteeMapper.java, src/main/java/com/yujigyeongseong/api/domain/research_number/dto/AcadAbility.java, src/main/java/com/yujigyeongseong/api/domain/research_number/dto/Career.java, src/main/java/com/yujigyeongseong/api/domain/research_number/dto/MemTechField.java, src/main/java/com/yujigyeongseong/api/domain/research_number/dto/TechField.java, src/main/java/com/yujigyeongseong/api/domain/research_number/dto/request/AcadRequest.java, src/main/java/com/yujigyeongseong/api/domain/research_number/dto/request/CareerRequest.java, src/main/java/com/yujigyeongseong/api/domain/research_number/dto/request/SubmitResearchRequest.java, src/main/java/com/yujigyeongseong/api/domain/research_number/service/EvalCommitteeService.java, src/main/java/com/yujigyeongseong/api/domain/research_number/service/EvalCommitteeServiceImpl.java, src/main/resources/api/mapper/h2/evalCommittee.xml, src/main/resources/data-h2.sql, src/main/webapp/WEB-INF/views/research-number/eval-committee-register.jsp, src/main/webapp/WEB-INF/views/research-number/research-number-page.jsp, src/main/webapp/resources/css/research-number/research-number.css, src/main/webapp/resources/js/research-number/research-number.js
<br/>
-  화면 오류 수정
- 연구자 번호 등록 ajax 구현
- DB 연동
<br/>
<br/>
=> 연구자 번호 발급 API를 구현한다. 

src/main/webapp/WEB-INF/views/announcement/apply-for-notice.jsp, src/main/webapp/resources/js/announcement/apply-for-notice.js
- [] FE
- [] BE
<br/>
- 연구계획서 접수 페이지 연동
<br/>
<br/>
- Close #이슈번호
<br/>
=> 회원 가입 API를 구현한다.

src/main/java/com/yujigyeongseong/api/domain/common/MainController.java, src/main/java/com/yujigyeongseong/api/domain/research_number/controller/EvalCommitteeRestController.java, src/main/java/com/yujigyeongseong/api/domain/research_number/controller/ResearchNumberController.java, src/main/java/com/yujigyeongseong/api/domain/research_number/controller/ResearchNumberRestController.java, src/main/java/com/yujigyeongseong/api/domain/research_number/dao/EvalComposeMapper.java, src/main/java/com/yujigyeongseong/api/domain/research_number/dto/request/EvalNotiRequest.java, src/main/java/com/yujigyeongseong/api/domain/research_number/service/EvalComposeService.java, src/main/java/com/yujigyeongseong/api/domain/research_number/service/EvalComposeServiceImpl.java, src/main/resources/api/mapper/announcement.xml, src/main/resources/api/mapper/evalCommittee.xml, src/main/resources/api/mapper/evalCompose.xml, src/main/resources/api/mapper/h2/evalCompose.xml, src/main/resources/api/mapper/rndPlan.xml, src/main/resources/api/mapper/techField.xml, src/main/resources/data-h2.sql, src/main/webapp/WEB-INF/views/rnd-plan/additional-file.jsp, src/main/webapp/WEB-INF/views/rnd-plan/rnd-expenses.jsp, src/main/webapp/WEB-INF/views/rnd-plan/rsrch-institution.jsp, src/main/webapp/WEB-INF/views/work-lounge/eval-committee-compose.jsp, src/main/webapp/resources/css/rnd-plan/common-rnd.css, src/main/webapp/resources/js/research-number/eval-committee-register.js, src/main/webapp/resources/js/research-number/research-number.js, src/main/webapp/resources/js/work-lounge/business-timeline.js, src/main/webapp/resources/js/work-lounge/eval-committee-compose.js
<br/>
- 메인화면 구성
- 연구개발 계획서 UI 구현
<br/>
<br/>
- Close #80 
- Close #83 
<br/>
=> 메인화면 구성, 평가위원 구성 구현하기, 연구개발 계획서 UI 구현하기

src/main/webapp/WEB-INF/views/announcement/announcement-list.jsp, src/main/webapp/WEB-INF/views/rnd-plan/additional-file.jsp, src/main/webapp/resources/css/rnd-plan/common-rnd.css, src/main/webapp/resources/js/rnd-plan/additional-file.js
<br/>
- tagify 버전 변경 및 브랜치 이동
<br/>
<br/>
=> tagify 버전 변경 및 브랜치 이동

src/main/java/com/yujigyeongseong/api/domain/research_number/controller/ResearchNumberRestController.java, src/main/java/com/yujigyeongseong/api/domain/research_number/dto/EvaluationMember.java, src/main/java/com/yujigyeongseong/api/domain/research_number/dto/request/MemberDetails.java, src/main/java/com/yujigyeongseong/api/domain/research_number/dto/request/MemberEvalRequest.java, src/main/webapp/WEB-INF/views/research-number/eval-committee-register.jsp, src/main/webapp/WEB-INF/views/research-number/research-number-page.jsp, src/main/webapp/WEB-INF/views/rnd-plan/rnd-expenses.jsp, src/main/webapp/WEB-INF/views/rnd-plan/rsrch-institution.jsp, src/main/webapp/WEB-INF/views/work-lounge/eval-committee-compose.jsp, src/main/webapp/resources/css/research-number/eval-committee-register.css, src/main/webapp/resources/css/research-number/research-number.css, src/main/webapp/resources/js/research-number/research-number.js, src/main/webapp/resources/js/rnd-plan/rsrch-institution.js, src/main/webapp/resources/js/work-lounge/eval-committee-compose.js
<br/>
- 계획서 페이지 API 연동 및 화면 수정
<br/>
- Close #93
<br/>
=> 계획서 페이지 API 연동 및 화면 수정

src/main/java/com/yujigyeongseong/api/domain/research_number/controller/ResearchNumberController.java, src/main/java/com/yujigyeongseong/api/domain/work_lounge/controller/WorkLoungeController.java, src/main/webapp/WEB-INF/views/common/common-work-lounge-tap.jsp, src/main/webapp/WEB-INF/views/sign-in-sign-up/sign-up-3.jsp, src/main/webapp/WEB-INF/views/work-lounge/evaluation-paper.jsp, src/main/webapp/WEB-INF/views/work-lounge/evaluation-task-list.jsp, src/main/webapp/WEB-INF/views/work-lounge/selection-evaluation-detail.jsp, src/main/webapp/WEB-INF/views/work-lounge/selection-evaluation.jsp, src/main/webapp/WEB-INF/views/work-lounge/sharing-opinion.jsp, src/main/webapp/resources/css/work-lounge/evaluation-paper.css, src/main/webapp/resources/css/work-lounge/evaluation-task-list.css, src/main/webapp/resources/css/work-lounge/selection-evaluation-detail.css, src/main/webapp/resources/css/work-lounge/sharing-opinion.css, src/main/webapp/resources/js/research-number/research-number.js, src/main/webapp/resources/js/work-lounge/evaluation-paper.js, src/main/webapp/resources/js/work-lounge/evaluation-task-list.js
- 제목 : feat(issue 번호): 기능명
ex) feat(17): pull request template 작성
(확인 후 지워주세요)
<br/>
- 기능에서 어떤 부분이
- 구현되었는지 설명해주세요
<br/>
<br/>
- Close #이슈번호
<br/>
=> bugfix : 링크 연결 / 페이지 합체

pom.xml, src/main/java/com/yujigyeongseong/api/domain/rnd_plan/controller/RndPlanRestController.java, src/main/java/com/yujigyeongseong/api/domain/rnd_plan/dao/RndPlanMapper.java, src/main/java/com/yujigyeongseong/api/domain/rnd_plan/dto/RndFee.java, src/main/java/com/yujigyeongseong/api/domain/rnd_plan/dto/request/CreateRndExpensesRequest.java, src/main/java/com/yujigyeongseong/api/domain/rnd_plan/dto/request/CreateRsrchInstitutionRequest.java, src/main/java/com/yujigyeongseong/api/domain/rnd_plan/dto/request/ResearchJoinPeriodRequest.java, src/main/java/com/yujigyeongseong/api/domain/rnd_plan/dto/request/ResearchRequest.java, src/main/java/com/yujigyeongseong/api/domain/rnd_plan/dto/response/CreateRsrchInstitutionResponse.java, src/main/java/com/yujigyeongseong/api/domain/rnd_plan/service/RndPlanService.java, src/main/java/com/yujigyeongseong/api/domain/rnd_plan/service/RndPlanServiceImpl.java, src/main/resources/api/mapper/rndPlan.xml, src/main/webapp/WEB-INF/views/rnd-plan/rnd-expenses.jsp, src/main/webapp/WEB-INF/views/rnd-plan/rsrch-institution.jsp, src/main/webapp/resources/js/rnd-plan/common-rnd-control.js, src/main/webapp/resources/js/rnd-plan/common-rnd-progress.js, src/main/webapp/resources/js/rnd-plan/rnd-expenses.js, src/main/webapp/resources/js/rnd-plan/rsrch-institution.js
<br/>
- 연구개발 계획서(연구 기관, 연구 개발비) API 구현
<br/>
- Close #99
<br/>
=> 연구개발 계획서(연구 기관, 연구 개발비) API 구현한다.

src/main/java/com/yujigyeongseong/api/domain/work_lounge/controller/WorkLoungeController.java, src/main/java/com/yujigyeongseong/api/domain/work_lounge/controller/WorkLoungeRestController.java, src/main/java/com/yujigyeongseong/api/domain/work_lounge/dao/SelectEvaluationMapper.java, src/main/java/com/yujigyeongseong/api/domain/work_lounge/dao/SharingOpinionMapper.java, src/main/java/com/yujigyeongseong/api/domain/work_lounge/dto/SharingOpinionDTO.java, src/main/java/com/yujigyeongseong/api/domain/work_lounge/service/EvaluationTableListServiceImpl.java, src/main/java/com/yujigyeongseong/api/domain/work_lounge/service/SelectEvaluationService.java, src/main/java/com/yujigyeongseong/api/domain/work_lounge/service/SelectEvaluationServiceImpl.java, src/main/java/com/yujigyeongseong/api/domain/work_lounge/service/SharingOpinionService.java, src/main/java/com/yujigyeongseong/api/domain/work_lounge/service/SharingOpinionServiceImpl.java, src/main/resources/api/mapper/evaluationTable.xml, src/main/resources/api/mapper/selectEvaluation.xml, src/main/resources/api/mapper/sharingOpinion.xml, src/main/webapp/WEB-INF/views/work-lounge/evaluation-table.jsp, src/main/webapp/resources/css/work-lounge/evaluation-table.css, src/main/webapp/resources/js/work-lounge/evaluation-table.js
<br/>
- evaluation-table 페이지 css 수정
<br/>
<br/>
- Close #이슈번호
<br/>
=> 선정 평가 상세 페이지 API를 수정한다.

src/main/java/com/yujigyeongseong/api/domain/research_number/controller/EvalCommitteeRestController.java, src/main/java/com/yujigyeongseong/api/domain/research_number/dto/request/EvalPercentRequest.java, src/main/java/com/yujigyeongseong/api/domain/rnd_plan/controller/RndPlanRestController.java, src/main/java/com/yujigyeongseong/api/domain/rnd_plan/dto/request/CreateBasicInfoRequest.java, src/main/webapp/WEB-INF/views/research-number/eval-committee-register.jsp, src/main/webapp/WEB-INF/views/work-lounge/eval-committee-compose.jsp, src/main/webapp/resources/css/research-number/eval-committee-register.css, src/main/webapp/resources/css/work-lounge/eval-committee-compose.css, src/main/webapp/resources/js/research-number/eval-committee-register.js, src/main/webapp/resources/js/research-number/research-number.js, src/main/webapp/resources/js/work-lounge/eval-committee-compose.js
<br/>
- 평가위원 구성 페이지 비율 적용 기능
- 평가위원 등록 전 공지 페이지 추가
<br/>
<br/>
- Close #103
<br/>
=> 평가위원 구성 페이지 비율 적용 기능을 구현한다.

src/main/java/com/yujigyeongseong/api/domain/research_number/controller/EvalCommitteeRestController.java, src/main/java/com/yujigyeongseong/api/domain/research_number/dao/EvalComposeMapper.java, src/main/java/com/yujigyeongseong/api/domain/research_number/service/EvalComposeService.java, src/main/java/com/yujigyeongseong/api/domain/research_number/service/EvalComposeServiceImpl.java, src/main/resources/api/mapper/evalCompose.xml, src/main/webapp/WEB-INF/views/work-lounge/eval-committee-compose.jsp, src/main/webapp/resources/css/work-lounge/eval-committee-compose.css, src/main/webapp/resources/js/work-lounge/eval-committee-compose.js
<br/>
- 평가위원 구성 비율 기능 구현
<br/>
<br/>
- Close #110
<br/>
=> 평가위원 구성 비율 기능 구현하기

pom.xml, src/main/java/com/yujigyeongseong/api/domain/research_number/config/WebSocketConfig.java, src/main/java/com/yujigyeongseong/api/domain/research_number/controller/ResearchNumberController.java, src/main/java/com/yujigyeongseong/api/domain/research_number/controller/ResearchNumberRestController.java, src/main/java/com/yujigyeongseong/api/domain/research_number/dto/response/NotiReponse.java, src/main/java/com/yujigyeongseong/api/domain/research_number/service/EvalCommitteeServiceImpl.java, src/main/java/com/yujigyeongseong/api/global/config/SecurityConfig.java, src/main/webapp/WEB-INF/views/common/common-header.jsp, src/main/webapp/WEB-INF/views/research-number/socket-test.jsp, src/main/webapp/resources/js/work-lounge/business-timeline.js
<br/>
- 웹소캣을 활용한 알림 환경설정 구현
<br/>
- Close #112
<br/>
=> 웹소캣을 활용한 알림 환경설정 구현하기

src/main/java/com/yujigyeongseong/api/domain/common_aws/EnvVariableProperties.java, src/main/java/com/yujigyeongseong/api/domain/common_aws/FileController.java, src/main/webapp/WEB-INF/views/announcement/detailed-notice.jsp, src/main/webapp/WEB-INF/views/work-lounge/eval-committee-compose.jsp, src/main/webapp/resources/css/work-lounge/eval-committee-compose.css, src/main/webapp/resources/js/announcement/detailed-notice.js
<br/>
- 평가위원 구성 화면 수정
- 첨부파일 다운로드 기능 구현
<br/>
=> 평가위원 구성 화면 수정, 첨부파일 다운로드 기능 구현하기

src/main/webapp/WEB-INF/views/main/index.jsp, src/main/webapp/WEB-INF/views/sign-in-sign-up/edit-personal-info.jsp, src/main/webapp/WEB-INF/views/sign-in-sign-up/member-delete.jsp, src/main/webapp/WEB-INF/views/sign-in-sign-up/sign-in.jsp, src/main/webapp/WEB-INF/views/sign-in-sign-up/sign-up-3.jsp, src/main/webapp/resources/css/announcement/apply-for-notice.css, src/main/webapp/resources/css/announcement/detailed-notice.css, src/main/webapp/resources/css/sign-in-sign-up/sign-in.css, src/main/webapp/resources/css/sign-in-sign-up/sign-up-2.css, src/main/webapp/resources/css/sign-in-sign-up/sign-up-3.css, src/main/webapp/resources/css/sign-in-sign-up/sign-up-4.css
- [] BE
<br/>
-  메인 페이지 디자인 수정
- 공모분야 페이지 디자인 수정
- 공고상세 페이지 디자인 수정
- 회원가입 페이지 디자인 수정
- 로그인 페이지 디자인 수정
- 개인정보 수정 페이지 디자인 수정
<br/>
- Close #123
<br/>
=> 화면 디자인을 수정한다.

src/main/java/com/yujigyeongseong/api/domain/rnd_plan/dao/RndPlanMapper.java, src/main/java/com/yujigyeongseong/api/domain/rnd_plan/service/RndPlanServiceImpl.java, src/main/java/com/yujigyeongseong/api/global/exception/GlobalRestControllerAdvice.java, src/main/resources/api/mapper/rndPlan.xml, src/main/webapp/resources/js/rnd-plan/common-rnd-control.js, src/main/webapp/resources/js/rnd-plan/common-rnd-progress.js
<br/>
- 계획서 페이지 저장 문제 해결
<br/>
=> 계획서 페이지 저장 문제 해결하기

src/main/java/com/yujigyeongseong/api/domain/work_lounge/controller/WorkLoungeRestController.java, src/main/java/com/yujigyeongseong/api/domain/work_lounge/dao/SelectEvaluationMapper.java, src/main/java/com/yujigyeongseong/api/domain/work_lounge/dto/UpdatePlanStatusDto.java, src/main/java/com/yujigyeongseong/api/domain/work_lounge/service/SelectEvaluationService.java, src/main/java/com/yujigyeongseong/api/domain/work_lounge/service/SelectEvaluationServiceImpl.java, src/main/resources/api/mapper/selectEvaluation.xml, src/main/webapp/WEB-INF/views/work-lounge/bubble-chart.jsp, src/main/webapp/WEB-INF/views/work-lounge/evaluation-paper.jsp, src/main/webapp/WEB-INF/views/work-lounge/evaluation-task-list.jsp, src/main/webapp/WEB-INF/views/work-lounge/register-list.jsp, src/main/webapp/WEB-INF/views/work-lounge/selection-evaluation-detail.jsp, src/main/webapp/WEB-INF/views/work-lounge/selection-evaluation.jsp, src/main/webapp/WEB-INF/views/work-lounge/sharing-opinion.jsp, src/main/webapp/resources/css/work-lounge/evaluation-task-list.css, src/main/webapp/resources/css/work-lounge/selection-evaluation-detail.css, src/main/webapp/resources/css/work-lounge/selection-evaluation.css, src/main/webapp/resources/css/work-lounge/sharing-opinion.css, src/main/webapp/resources/js/work-lounge/evaluation-task-list.js, src/main/webapp/resources/js/work-lounge/register-list.js, src/main/webapp/resources/js/work-lounge/selection-evaluation.js, src/main/webapp/resources/js/work-lounge/sharing-opinion.js
- 제목 : feat(issue 번호): 기능명
ex) feat(17): pull request template 작성
(확인 후 지워주세요)
<br/>
- 의견공유 대댓글 기능 수정
- 선정 평가 상세 선정 기능 수정
- 선정확정시 평가상태 변경 기능 추가
<br/>
<br/>
- Close #120 
<br/>
=> 전자평가표 저장 API 기능을 구현한다.

src/main/java/com/yujigyeongseong/api/domain/announcement/controller/AnnouncementController.java, src/main/java/com/yujigyeongseong/api/domain/announcement/controller/AnnouncementRestController.java, src/main/java/com/yujigyeongseong/api/domain/announcement/dao/AnnouncementMapper.java, src/main/java/com/yujigyeongseong/api/domain/announcement/dto/AnnocementFile.java, src/main/java/com/yujigyeongseong/api/domain/announcement/service/AnnouncementListService.java, src/main/java/com/yujigyeongseong/api/domain/common_aws/AwsS3Utils.java, src/main/java/com/yujigyeongseong/api/domain/common_aws/FileController.java, src/main/java/com/yujigyeongseong/api/domain/member/service/MailService.java, src/main/resources/api/mapper/announcement.xml, src/main/webapp/WEB-INF/views/announcement/apply-for-notice.jsp, src/main/webapp/WEB-INF/views/announcement/detailed-notice.jsp, src/main/webapp/WEB-INF/views/sign-in-sign-up/sign-up-3.jsp, src/main/webapp/resources/js/announcement/apply-for-notice.js, src/main/webapp/resources/js/announcement/detailed-notice.js, src/main/webapp/resources/js/rnd-plan/additional-file.js
<br/>
- s3파일 업로드 다운로드 기능을 구현
<br/>
- Close #125 
<br/>
=> s3파일 업로드 다운로드 기능을 구현한다.

src/main/java/com/yujigyeongseong/api/domain/research_number/service/EvalComposeServiceImpl.java, src/main/webapp/WEB-INF/views/rnd-plan/rnd-expenses.jsp
<br/>
- 기능에서 어떤 부분이
- 구현되었는지 설명해주세요
<br/>
- Close #이슈번호
<br/>
=> feature : 연구개발비 화면 구성 변경 [#130]

src/main/java/com/yujigyeongseong/api/domain/announcement/controller/AnnouncementRestController.java, src/main/java/com/yujigyeongseong/api/domain/announcement/dao/AnnouncementMapper.java, src/main/resources/api/mapper/announcement.xml, src/main/webapp/resources/js/main/main.js
- [] DESIGN
- [] FE
<br/>
- 공고 페이지 필터링기능을 수정
<br/>
- Close #138 
<br/>
=> 공고 페이지 필터링기능을 수정한다.

src/main/java/com/yujigyeongseong/api/domain/research_number/config/WebSocketConfig.java, src/main/webapp/WEB-INF/views/rnd-plan/final-submit.jsp, src/main/webapp/resources/js/announcement/detailed-notice.js, src/main/webapp/resources/js/research-number/research-number.js, src/main/webapp/resources/js/rnd-plan/final-submit.js, src/main/webapp/resources/js/sign-in-sign-up/edit-personal-info.js, src/main/webapp/resources/js/sign-in-sign-up/sign-up-3.js
<br/>
- 최종 페이지 디자인 변경, alert 변경
<br/>
<br/>
- Close #이슈번호
<br/>
=> 최종 페이지 디자인 변경, alert 변경
